# Generated by Django 2.2 on 2019-08-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_no_or_name', models.CharField(max_length=200)),
                ('add_line_1', models.CharField(max_length=1000)),
                ('add_line_2', models.CharField(max_length=1000)),
                ('zip_code', models.CharField(max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
